import type { Metadata } from "next";
import { Providers } from "./provider";
import { quicksand } from "@/utils/fonts";
import "@/styles/globals.scss";
import "mac-scrollbar/dist/mac-scrollbar.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Gohub cloud",
  description: "Generated by create next app"
};

interface RootLayoutProps {
  children: ReactNode;
}
const RootLayout = (props: RootLayoutProps) => {
  const { children} = props;
  

  return (
    <html lang="en">
      <link
        rel="shortcut icon"
        href="/logo.png"
        type="image/x-icon"
        sizes="any"
      />
      <body className={quicksand.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

export default RootLayout;