import { SelectProps, Tag } from 'antd';

export const dayAmountOptions: SelectProps['options'] = [
  { value: '01', label: '01' },
  { value: '02', label: '02' },
  { value: '03', label: '03' },
  { value: '04', label: '04' },
  { value: '05', label: '05' },
  { value: '06', label: '06' },
  { value: '07', label: '07' },
  { value: '08', label: '08' },
  { value: '09', label: '09' },
  { value: '10', label: '10' },
  { value: '11', label: '11' },
  { value: '12', label: '12' },
  { value: '13', label: '13' },
  { value: '14', label: '14' },
  { value: '15', label: '15' },
  { value: '16', label: '16' },
  { value: '17', label: '17' },
  { value: '18', label: '18' },
  { value: '19', label: '19' },
  { value: '20', label: '20' },
  { value: '21', label: '21' },
  { value: '22', label: '22' },
  { value: '23', label: '23' },
  { value: '24', label: '24' },
  { value: '25', label: '25' },
  { value: '26', label: '26' },
  { value: '27', label: '27' },
  { value: '28', label: '28' },
  { value: '29', label: '29' },
  { value: '30', label: '30' },
  { value: '31', label: '31' },
] as const;

export const dataAmountOptions: SelectProps['options'] = [
  { value: '500M', label: <Tag color="blue">500MB</Tag> },
  { value: '01GB', label: <Tag color="blue">01GB</Tag> },
  { value: '02GB', label: <Tag color="blue">02GB</Tag> },
  { value: '03GB', label: <Tag color="blue">03GB</Tag> },
  { value: '04GB', label: <Tag color="blue">04GB</Tag> },
  { value: '05GB', label: <Tag color="blue">05GB</Tag> },
  { value: '06GB', label: <Tag color="blue">06GB</Tag> },
  { value: '07GB', label: <Tag color="blue">07GB</Tag> },
  { value: '08GB', label: <Tag color="blue">08GB</Tag> },
  { value: '09GB', label: <Tag color="blue">09GB</Tag> },
  { value: '10GB', label: <Tag color="blue">10GB</Tag> },
  { value: '15GB', label: <Tag color="blue">15GB</Tag> },
  { value: '20GB', label: <Tag color="blue">20GB</Tag> },
  { value: '25GB', label: <Tag color="blue">25GB</Tag> },
  { value: '30GB', label: <Tag color="blue">30GB</Tag> },
  { value: '40GB', label: <Tag color="blue">40GB</Tag> },
  { value: '50GB', label: <Tag color="blue">50GB</Tag> },
  { value: '60GB', label: <Tag color="blue">60GB</Tag> },
  { value: '70GB', label: <Tag color="blue">70GB</Tag> },
  { value: '80GB', label: <Tag color="blue">80GB</Tag> },
  { value: '90GB', label: <Tag color="blue">90GB</Tag> },
  { value: '100GB', label: <Tag color="blue">100GB</Tag> },
  { value: '150GB', label: <Tag color="blue">150GB</Tag> },
  { value: '200GB', label: <Tag color="blue">200GB</Tag> },
  { value: '250GB', label: <Tag color="blue">250GB</Tag> },
  { value: '300GB', label: <Tag color="blue">300GB</Tag> },
  { value: '400GB', label: <Tag color="blue">400GB</Tag> },
  { value: '500GB', label: <Tag color="blue">500GB</Tag> },
  { value: '600GB', label: <Tag color="blue">600GB</Tag> },
  { value: '700GB', label: <Tag color="blue">700GB</Tag> },
  { value: '800GB', label: <Tag color="blue">800GB</Tag> },
  { value: '900GB', label: <Tag color="blue">900GB</Tag> },
  { value: '01TB', label: <Tag color="blue">01TB</Tag> },
] as const;
